/*
 * generated by Xtext 2.23.0
 */
package fr.insa.exp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExpUiModule extends AbstractExpUiModule {

	public ExpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
