/*
 * generated by Xtext 2.23.0
 */
package fr.insa.exp.validation;

import org.eclipse.xtext.validation.Check;

import fr.insa.exp.exp.Div;
import fr.insa.exp.exp.ExpPackage;
import fr.insa.exp.exp.Literal;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ExpValidator extends AbstractExpValidator {
	
	public static final String DIV_0 = "0-div";
	public static final String DIV_0_MSG = "Cannot divide by 0";
	
	public static final String INV_REF = "invalid-ref";
	public static final String INV_REF_MSG = "This value does not exist";
			
	@Check
	public void checkDiv0(Div division) {
		if (division.getRightOp() instanceof Literal && Double.compare(0d, ((Literal) division.getLeftOp()).getValue()) == 0) {
			error(DIV_0_MSG, ExpPackage.Literals.OPERANDS__LEFT_OP, DIV_0);
		}
	}
	
}
