/*
 * generated by Xtext 2.23.0
 */
package fr.insa.exp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.insa.exp.ExpRuntimeModule;
import fr.insa.exp.ExpStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExpIdeSetup extends ExpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExpRuntimeModule(), new ExpIdeModule()));
	}
	
}
