/*
 * generated by Xtext 2.23.0
 */
package fr.insa.exp;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExpStandaloneSetup extends ExpStandaloneSetupGenerated {

	public static void doSetup() {
		new ExpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
